---
swagger: "2.0"
info:
  x-ibm-name: "catalog"
  title: "catalog"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/api"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - set-variable:
        title: "set-variable"
        actions:
        - set: "bluecompute.iss.claim"
          value: "apic"
        - set: "hs256-key"
          value: "{ \"alg\": \"HS256\",   \"kty\": \"oct\",   \"use\": \"sig\",  \
            \ \"k\": \"l6kHLmBzbzdBi8eznmg-nGP3pZihFpLgie0K-SKEUARXzyG5yJ7nnZoFPVL_MvoJckcoRslQZlxsNZpVruKqrP0s-m6YDaKw4Ody8lZbPmQ7wU0Mc1561J01VH55s4apg_TvnOJ6xn8sEfid3gPbvXntIb0hokVtopG5Zaam2wfyMuBlzqhQ42TtL51yZOym5NLad4_WtZUG9kM204K7OgLHFfUABpWD4ocBF7uQrebcO4cwqlVI6N_A_252TdEkfOyh_vG4yxO0h88LxaGSXj0iKFpO4q6md7bFMjzdehtPKiqWktKg02QyAjq-PRcrSiWBZfh2w6JIkU7g8kS5YQ\"\
            \ }"
        - set: "service-name"
          value: "$(MICROSERVICE_NAME)"
        version: "1.0.0"
        description: "Define variables"
    - jwt-generate:
        title: "jwt-generate"
        iss-claim: "bluecompute.iss.claim"
        exp-claim: 3600
        version: "1.0.0"
        sub-claim: ""
        jws-alg: "HS256"
        jwt: "jwttoken"
        jwe-enc: "A128CBC-HS256"
        jwe-alg: "A256KW"
        jws-jwk: "hs256-key"
    - gatewayscript:
        title: "gateway-script"
        version: "1.0.0"
        source: "var path = apim.getvariable('request.path');\nvar service = apim.getvariable('service-name')\n\
          \n// translate path\nvar realpath = path.replace('/api', '/' + service +\
          \ '/micro');\napim.setvariable('real-path', realpath);\n\n// set JWT token\n\
          apim.setvariable('message.headers.authorization', 'Bearer ' + apim.getvariable('jwttoken')); "
    - invoke:
        target-url: "$(TARGET_HOST)$(real-path)"
    catch: []
  phase: "realized"
  properties:
    TARGET_HOST:
      value: 'https://us-netflix-zuul-jkwong-dev.mybluemix.net'
      description: ""
      encoded: false
    MICROSERVICE_NAME:
      value: "catalog-microservice"
      description: ""
      encoded: false
  catalogs: {}
paths:
  /items/{id}:
    get:
      responses:
        200:
          description: "200 OK"
    parameters:
    - name: "id"
      type: "integer"
      required: true
      in: "path"
      format: "int32"
  /items:
    get:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/itemArray"
definitions:
  itemArray:
    type: "array"
    items:
      $ref: "#/definitions/item"
  item:
    properties:
      stock:
        type: "integer"
        format: "int32"
      img:
        type: "string"
      imgAlt:
        type: "string"
      price:
        type: "integer"
        format: "int32"
      description:
        type: "string"
      name:
        type: "string"
      id:
        type: "integer"
        format: "int32"
    additionalProperties: false
tags: []
