---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "oauth"
  x-ibm-name: "oauth-provider"
host: "$(catalog.host)"
basePath: "/oauth20"
paths:
  /authorize:
    get:
      produces:
      - "text/html"
      summary: "endpoint for Authorization Code and Implicit grants"
      description: "description"
      parameters:
      - name: "response_type"
        in: "query"
        description: "request an authorization code or or access token (implicit)"
        required: true
        type: "string"
        enum:
        - "code"
        - "token"
      - name: "client_id"
        in: "query"
        description: "Application client ID"
        required: true
        type: "string"
      - name: "scope"
        in: "query"
        description: "Scope being requested"
        type: "string"
        required: true
      - name: "redirect_uri"
        in: "query"
        type: "string"
        description: "URI where user is redirected to after authorization"
        required: false
      - name: "state"
        in: "query"
        type: "string"
        description: "This string will be echoed back to application when user is\
          \ redirected"
        required: false
      responses:
        200:
          description: "An HTML form for authentication or authorization of this request."
        302:
          description: "Redirect to the clients redirect_uri containing one of the\
            \ following\n- **authorization code** for Authorization code grant\n-\
            \ **access token** for Implicity grant\n- **error** in case of errors,\
            \ such as the user has denied the request\n"
      security:
      - clientID: []
    post:
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "text/html"
      summary: "submit approval to authorization code or access token"
      description: "Submit resource owners approval (or rejection) for the OAuth2\
        \ Server to issue an\nauthorization code or access token to the application.\n"
      security:
      - clientID: []
      parameters:
      - name: "client_id"
        in: "formData"
        description: "application requesting the access code or token"
        required: true
        type: "string"
      - name: "scope"
        in: "formData"
        description: "requested scope of this authorization"
        required: true
        type: "string"
      - name: "resource-owner"
        in: "formData"
        description: "resource owners user name"
        required: true
        type: "string"
      - name: "redirect_uri"
        in: "formData"
        description: "URI the application is requesting this code or token to be redirected\
          \ to"
        required: true
        type: "string"
      - name: "original-url"
        in: "formData"
        description: "URL of the original authorization request"
        required: true
        type: "string"
      - name: "dp-state"
        in: "formData"
        description: "state information provided in the authorization form"
        required: true
        type: "string"
      - name: "dp-data"
        in: "formData"
        description: "state information provided in the authorization form"
        required: true
        type: "string"
      responses:
        200:
          description: "Cool"
  /token:
    post:
      consumes:
      - "application/x-www-form-urlencoded"
      - "multipart/form-data"
      produces:
      - "application/json"
      summary: "Request Access Tokens"
      description: "This endpoint allows requesting an access token following one\
        \ of the flows below:\n- Authorization Code (exchange code for access token)\n\
        - Client Credentials (2-legged, there isnt resource owner information)\n-\
        \ Resource Owner Password Credentials (2-legged, client provides resource\
        \ owner name and password)\n- Refresh Token (exchange refresh token for a\
        \ new access code)\n\nThe table below indicates the required parameters for\
        \ each specific grant_type options.\nEmpty cells indicate a parameter is ignored\
        \ for that specific grant type.\n\nClient authentication:\n- Confidential\
        \ clients should authenticate using HTTP Basic Authentication. Alternatively,\
        \ they may post\n  their client_id and client_secret information as a formData\
        \ parameter.\n- Public clients should send their client_id as formData parameter.\n\
        \n| grant_type           | code       | client_credentials | password    |\
        \ refresh_token |\n|----------------------|------------|--------------------|-------------|---------------|\n\
        | client_id            | required*  | required*          | required*   | required*\
        \     |\n| client_secret        | required*  | required*          | required*\
        \   | required*     |\n| code                 | required   |             \
        \       |             |               |\n| redirect_uri         | required\
        \   |                    |             |               |\n| username     \
        \        |            |                    | required    |               |\n\
        | password             |            |                    | required    | \
        \              |\n| scope                |            | optional         \
        \  | optional    |               |\n| refresh_token        |            |\
        \                    |             | required      |\n\nThe implicit grant\
        \ requests, see /oauth2/authorize.\n"
      parameters:
      - name: "grant_type"
        in: "formData"
        description: "Type of grant"
        type: "string"
        required: true
        enum:
        - "authorization_code"
        - "password"
        - "client_credentials"
        - "refresh_token"
      - name: "client_id"
        in: "formData"
        description: "Application client ID, can be provided in formData or using\
          \ HTTP Basic Authentication"
        required: true
        type: "string"
      - name: "client_secret"
        in: "formData"
        description: "Application secret, must be provided in formData or using HTTP\
          \ Basic Authentication"
        required: false
        type: "string"
      - name: "code"
        in: "formData"
        description: "Authorization code provided by the /oauth2/authorize endpoint"
        required: true
        type: "string"
      - name: "redirect_uri"
        in: "formData"
        description: "required only if the redirect_uri parameter was included in\
          \ the authorization request /oauth2/authorize; their values MUST be identical."
        required: true
        type: "string"
      - name: "username"
        in: "formData"
        type: "string"
        description: "Resource owner username"
        required: false
      - name: "password"
        in: "formData"
        type: "string"
        description: "Resource owner password"
        required: false
      - name: "scope"
        in: "formData"
        type: "string"
        description: "Scope being requested"
        required: false
      - name: "refresh_token"
        in: "formData"
        type: "string"
        description: "The refresh token that the client wants to exchange for a new\
          \ access token (refresh_token grant_type)"
        required: false
      responses:
        200:
          description: "json document containing token, etc."
          schema:
            $ref: "#/definitions/access_token_response"
        400:
          description: "json document that may contain additional details about the\
            \ failure"
      security: []
  /introspect:
    post:
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      summary: "Introspect a given access_token supported"
      description: "This endpoint introspects a given access_token\n"
      security:
      - clientIdHeader: []
      parameters:
      - name: "token"
        in: "formData"
        description: "String value of the access_token to be introspected"
        required: true
        type: "string"
      - name: "token_type_hint"
        in: "formData"
        description: "This must contain 'access_token' to indicate the token type"
        required: true
        type: "string"
      responses:
        200:
          description: "json document containing issued information, etc."
          schema:
            $ref: "#/definitions/introspect_response"
        401:
          description: "failure"
securityDefinitions:
  clientID:
    description: ""
    in: "query"
    name: "client_id"
    type: "apiKey"
  clientIdHeader:
    in: "header"
    type: "apiKey"
    name: "X-IBM-Client-Id"
security:
- {}
x-ibm-configuration:
  testable: true
  enforced: true
  phase: "realized"
  oauth2:
    client-type: "public"
    scopes:
      blue: "bluecompute scope"
    grants:
    - "accessCode"
    - "implicit"
    - "password"
    identity-extraction:
      type: "custom-form"
      custom-form:
        url: "https://us-micro-auth-cloudnative-integration.mybluemix.net/login.html"
      redirect-url: "https://us-micro-auth-cloudnative-integration.mybluemix.net/authenticate"
    authentication:
      x-ibm-authentication-url:
        url: "https://us-micro-auth-cloudnative-integration.mybluemix.net/authenticate"
        tls-profile: ""
    authorization:
      type: "authenticated"
      custom-form:
        url: "https://us-micro-auth-cloudnative-integration.mybluemix.net/grant.html"
    refresh-token:
      count: 2048
      ttl: 2682000
    access-token:
      ttl: 3600
  cors:
    enabled: true
  type: "oauth"
schemes:
- "https"
definitions:
  access_token_response:
    type: "object"
    additionalProperties: false
    required:
    - "token_type"
    - "access_token"
    - "expires_in"
    - "refresh_token"
    - "scope"
    properties:
      token_type:
        enum:
        - "bearer"
      access_token:
        type: "string"
      expires_in:
        type: "integer"
      scope:
        type: "string"
      refresh_token:
        type: "string"
  introspect_response:
    type: "object"
    additionalProperties: false
    required:
    - "active"
    - "client_id"
    - "client_name"
    - "username"
    - "sub"
    - "exp"
    - "expstr"
    - "iat"
    - "nbf"
    - "nbfstr"
    - "scope"
    properties:
      active:
        type: "boolean"
      client_id:
        type: "string"
      client_name:
        type: "string"
      username:
        type: "string"
      sub:
        type: "string"
      exp:
        type: "string"
      expstr:
        type: "string"
      iat:
        type: "string"
      nbf:
        type: "string"
      nbfstr:
        type: "string"
      scope:
        type: "string"
      miscinfo:
        type: "string"
